// MTG keyword abilities and oracle-text strategy terms, sorted alphabetically
const MTG_KEYWORDS: string[] = [
	"Absorb","Affinity","Afflict","Afterlife","Aftermath","Airbend","Amplify","Annihilator",
	"Aristocrats","Ascend","Assist","Augment","Aura","Aura Swap","Awaken","Backup",
	"Banding","Bargain","Basic landcycling","Battle Cry","Bestow","Blink","Blitz","Bloodthirst",
	"Boast","Bushido","Buyback","Cantrip","Cascade","Casualty","Champion","Changeling",
	"Choose a background","Cipher","Cleave","Commander ninjutsu","Companion","Compleated","Conspire","Constellation",
	"Control","Convoke","Copy","Counters","Craft","Crew","Cumulative upkeep","Cycling",
	"Dash","Daybound","Deathtouch","Decayed","Defender","Delve","Demonstrate","Desertwalk",
	"Dethrone","Devoid","Devour","Discard","Disguise","Disturb","Doctor's companion","Double agenda",
	"Double strike","Double team","Drain","Draw","Dredge","Earthbend","Echo","Embalm",
	"Emerge","Enchant","Enchantress","Encore","Enlist","Entwine","Epic","Equip",
	"Equipment","Escalate","Escape","Eternalize","Evoke","Evolve","Exalted","Exhaust",
	"Exploit","Extort","Fabricate","Fading","Fear","Firebending","First strike","Flanking",
	"Flash","Flashback","Flicker","Flying","For Mirrodin!","Forecast","Forestcycling","Forestwalk",
	"Foretell","Fortify","Freerunning","Frenzy","Friends forever","Fuse","Gift","Graft",
	"Gravestorm","Graveyard","Harmonize","Haste","Haunt","Hexproof","Hexproof from","Hidden agenda",
	"Hideaway","Horsemanship","Impending","Improvise","Increment","Indestructible","Infect","Ingest",
	"Intensity","Intimidate","Islandcycling","Islandwalk","Job select","Jump-start","Kicker","Landcycling",
	"Landfall","Landwalk","Legendary landwalk","Level Up","Lifegain","Lifelink","Living metal","Living weapon",
	"Loot","Madness","Magecraft","Max speed","Mayhem","Megamorph","Melee","Menace",
	"Mentor","Metalbend","Mill","Miracle","Mobilize","Modular","More Than Meets the Eye","Morph",
	"Mountaincycling","Mountainwalk","Multikicker","Mutate","Myriad","Nightbound","Ninjutsu","Nonbasic landwalk",
	"Offering","Offspring","Outlast","Overload","Paradigm","Partner","Partner with","Persist",
	"Phasing","Plainscycling","Plainswalk","Poisonous","Populate","Proliferate","Protection","Prototype",
	"Provoke","Prowess","Prowl","Ramp","Rampage","Ravenous","Reach","Read Ahead",
	"Reanimate","Rebound","Reconfigure","Recover","Recursion","Reinforce","Renown","Replicate",
	"Retrace","Riot","Ripple","Sacrifice","Saddle","Scavenge","Scry","Shadow",
	"Shroud","Skulk","Slivercycling","Sneak","Solved","Soulbond","Soulshift","Specialize",
	"Spectacle","Spellslinger","Splice","Split second","Spree","Squad","Station","Stax",
	"Storm","Sunburst","Surge","Surveil","Suspend","Swampcycling","Swampwalk","Tap",
	"Tiered","Token","Toxic","Training","Trample","Transfigure","Transmute","Tribal",
	"Tribute","Typecycling","Umbra armor","Undaunted","Undying","Unearth","Unleash","Untap",
	"Vanishing","Vigilance","Voltron","Ward","Warp","Waterbend","Web-slinging","Wither",
	"Wizardcycling",
];

export default MTG_KEYWORDS;
